create table cake (CID varchar(5) primary key, FLAVOURS VARCHAR(40), PRICE_PER_KG INT ,TOPPING VARCHAR(30),PRICE INT ,TOTAL_AMOUNT INT, DURATION_IN_HRS  INT);

INSERT INTO CAKE VALUES("CC1","DARK CHOCOLATE",185,"CHOCOLATE CHIPS N CHERRY",35,220,2);

INSERT INTO CAKE VALUES("CC2","CHOCOLATE TRUFFLE",200,"CHOCOLATE CHIPS ",25,225,2);

INSERT INTO CAKE VALUES("CS1","STRAWBERRY BONANZA",210,"CHERRY N STRAWBERRY",50,260,3);

INSERT INTO CAKE VALUES("CB1","BLACK FOREST",190,"NUTS N EXTRA CREAM",60,250,2);

INSERT INTO CAKE VALUES("CP1","PINEAPPLE SUPRISE",260,"JELLY N GEMS",40,300,3);

INSERT INTO CAKE VALUES("CV1","VANILLA FRESH",160,"VANILLA ICING N STRAWBERRY",60,250,2);

INSERT INTO CAKE VALUES("CV2","VANILLA DELIGHT",180," HOT CHOCOLATE",60,250,2);

