create table cookie (CID varchar(5) primary key, TYPE VARCHAR(40), PRICE_PER_PIECE INT);

INSERT INTO  cookie VALUES("C1","CHOCOLATE CHIP",25);

INSERT INTO cookie VALUES("C2","COFFEE MIX ",30);

INSERT INTO cookie VALUES("C3","CASHEWNUT ",40);

INSERT INTO cookie VALUES("C4","ALMOND",35);

INSERT INTO cookie VALUES("C5","OATMEAL",20);

INSERT INTO cookie  VALUES("C6","WALNUT",25);

INSERT INTO cookie VALUES("C7","D n D SPECIAL",45);

