create table doughnut (CID varchar(5) primary key, FLAVOURS VARCHAR(40), PRICE_PER_PIECE INT );

INSERT INTO doughnut VALUES("D1","CHOCOLATE",40);

INSERT INTO doughnut  VALUES("D2","WALNUT",30);

INSERT INTO doughnut VALUES("D3","ORANGE SUPRISE",30);

INSERT INTO doughnut VALUES("D4","GEMS DELIGHT",35);

INSERT INTO doughnut  VALUES("D5","STRAWBERRY TUMBLER",40);

INSERT INTO doughnut VALUES("D6","HOT CHOCOLATE",25);



