create table pastry (CID varchar(5) primary key, FLAVOURS VARCHAR(40), PRICE_PER_PIECE INT );

INSERT INTO pastry VALUES("P1","ECLAIRS",40);

INSERT INTO pastry  VALUES("P2","BUTTER SCOTCH",30);

INSERT INTO pastry  VALUES("P3","BLACK CURRENT",30);

INSERT INTO pastry VALUES("P4","BLACK FOREST",35);

INSERT INTO pastry  VALUES("P5","PINEAPPLE",40);

INSERT INTO pastry VALUES("P6","VANILLA",25);

INSERT INTO pastry  VALUES("P7","BLUE BERRY",40);

