import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cake.java
 *
 * Created on Oct 23, 2013, 12:24:57 PM
 */

/**
 *
 * @author lab2
 */
public class cake extends javax.swing.JFrame {

    /** Creates new form cake */
    public cake() {
        initComponents();
        getContentPane().setBackground(Color.decode("#fdffcc"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcpic = new javax.swing.JLabel();
        border = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ccrange = new javax.swing.JComboBox();
        tcvalue = new javax.swing.JTextField();
        bselcake = new javax.swing.JButton();
        bshowall = new javax.swing.JButton();
        bcclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcakes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAKES !!");

        border.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        border.setText("ORDER");
        border.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRICE  RANGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR JULIAN", 0, 12))); // NOI18N

        ccrange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<", ">", "<=", ">=", "=" }));

        bselcake.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bselcake.setText("SELECTION");
        bselcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselcakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bselcake))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ccrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(tcvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bselcake)
                .addContainerGap())
        );

        bshowall.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bshowall.setText("SHOW ALL CAKES");
        bshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bshowallActionPerformed(evt);
            }
        });

        bcclear.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bcclear.setText("CLear");
        bcclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcclearActionPerformed(evt);
            }
        });

        tcakes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "TYPE", "PRICE PER PIECE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcakesMouseClicked(evt);
            }
        });
        tcakes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcakesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tcakes);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("cake menU !!");

        back.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        back.setText("BACK TO MAIN PAGE");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcpic, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bshowall)
                                .addGap(18, 18, 18)
                                .addComponent(bcclear)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(border)
                                        .addGap(50, 50, 50)))
                                .addContainerGap(95, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(border)
                        .addGap(57, 57, 57)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bshowall)
                            .addComponent(bcclear))
                        .addGap(30, 30, 30)
                        .addComponent(lcpic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderActionPerformed
        DefaultTableModel dm1= (DefaultTableModel)tcakes.getModel();
        int i=tcakes.getSelectedRow();
        //System.out.print("  "+i);
        String name=(String) dm1.getValueAt(i, 1);
        Object pr=dm1.getValueAt(i,2);
        new bill(name,pr).setVisible(true);
}//GEN-LAST:event_borderActionPerformed

    private void bselcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselcakeActionPerformed
        bcclear.doClick();
        DefaultTableModel dm=(DefaultTableModel)tcakes.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
            //System.out.println("connected");
            Statement s1=con.createStatement();
            String sym=(String)ccrange.getSelectedItem();

            int Val=Integer.parseInt(tcvalue.getText());
            String sql="Select * from Cake where price_per_kg"+sym+Val+";";
            ResultSet r1=s1.executeQuery(sql);
            String  id=null,name=null;
            int price=0;
            while(r1.next()) {
                id=r1.getString(1);
                name =r1.getString(2);
                price=r1.getInt(3);
                dm.addRow(new Object[]{id,name,price});
            }


        } catch(Exception ex) {
            System.out.println(ex);
        }   
        
        tcakes.changeSelection(0, 0, false, false);
        int j=tcakes.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm.getValueAt(j, 0);
        if(pic.equals("CB1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/black_forest.jpeg")));
        if(pic.equals("CC1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/dark_chocolate.jpg")));
        if(pic.equals("CC2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/chocolate_truffle.jpg")));
        if(pic.equals("CP1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/pineapple_cake.jpg")));
        if(pic.equals("CS1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/strawberry_cake.jpg")));
        if(pic.equals("CV1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/vanilla_cake.jpg")));
        if(pic.equals("CV2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco_vanilla_delight.jpg")));

        
        tcakes.requestFocus();
        tcakes.editCellAt(0,1);
// TODO add your handling code here:
}//GEN-LAST:event_bselcakeActionPerformed

    private void bshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bshowallActionPerformed
        bcclear.doClick();
        DefaultTableModel dm=(DefaultTableModel)tcakes.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
            //System.out.println("connected");
            Statement s1=con.createStatement();
            String sql="Select * from Cake;";
            ResultSet r1=s1.executeQuery(sql);
            String  id=null,name=null;
            int price=0;
            while(r1.next()) {
                id=r1.getString(1);
                name =r1.getString(2);
                price=r1.getInt(3);
                dm.addRow(new Object[]{id,name,price});
            }


        } catch(Exception ex) {
            System.out.println(ex);
        }
        
        tcakes.changeSelection(0, 0, false, false);
        int j=tcakes.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm.getValueAt(j, 0);
        if(pic.equals("CB1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/black_forest.jpeg")));
        
        tcakes.requestFocus();
        tcakes.editCellAt(0,1);
        // TODO add your handling code here:
}//GEN-LAST:event_bshowallActionPerformed

    private void bcclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcclearActionPerformed
        //tcvalue.setText("");
        DefaultTableModel dm=(DefaultTableModel)tcakes.getModel();
        int rc=dm.getRowCount();
        for(int i=rc-1;i>=0;i--)
            dm.removeRow(i);
        lcpic.setIcon(null);
        // TODO add your handling code here:
}//GEN-LAST:event_bcclearActionPerformed

    private void tcakesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcakesMouseClicked
        DefaultTableModel dm1= (DefaultTableModel)tcakes.getModel();
        int j=tcakes.getSelectedRow();
       // System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("CB1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/black_forest.jpeg")));
        if(pic.equals("CC1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/dark_chocolate.jpg")));
        if(pic.equals("CC2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/chocolate_truffle.jpg")));
        if(pic.equals("CP1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/pineapple_cake.jpg")));
        if(pic.equals("CS1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/strawberry_cake.jpg")));
        if(pic.equals("CV1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/vanilla_cake.jpg")));
        if(pic.equals("CV2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco_vanilla_delight.jpg")));
        // TODO add your handling code here:
    }//GEN-LAST:event_tcakesMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void tcakesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcakesKeyReleased
        DefaultTableModel dm1= (DefaultTableModel)tcakes.getModel();
        int j=tcakes.getSelectedRow();
       // System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("CB1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/black_forest.jpeg")));
        if(pic.equals("CC1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/dark_chocolate.jpg")));
        if(pic.equals("CC2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/chocolate_truffle.jpg")));
        if(pic.equals("CP1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/pineapple_cake.jpg")));
        if(pic.equals("CS1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/strawberry_cake.jpg")));
        if(pic.equals("CV1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/vanilla_cake.jpg")));
        if(pic.equals("CV2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco_vanilla_delight.jpg")));        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_tcakesKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bcclear;
    private javax.swing.JButton border;
    private javax.swing.JButton bselcake;
    private javax.swing.JButton bshowall;
    private javax.swing.JComboBox ccrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcpic;
    private javax.swing.JTable tcakes;
    private javax.swing.JTextField tcvalue;
    // End of variables declaration//GEN-END:variables

}
