import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cookies.java
 *
 * Created on Nov 20, 2012, 10:05:30 AM
 */

/**
 *
 * @author optional
 */
public class cookies extends javax.swing.JFrame {

    /** Creates new form cookies */
    public cookies() {
        initComponents();
        getContentPane().setBackground(Color.decode("#fdffcc"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcookies = new javax.swing.JTable();
        bshowall = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ccrange = new javax.swing.JComboBox();
        tcvalue = new javax.swing.JTextField();
        bselcookies = new javax.swing.JButton();
        bcclear = new javax.swing.JButton();
        lcpic = new javax.swing.JLabel();
        border = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COOKIES !!");

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel1.setText("cookie MENU !!");

        tcookies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "TYPE", "PRICE PER PIECE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcookies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcookiesMouseClicked(evt);
            }
        });
        tcookies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcookiesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tcookies);

        bshowall.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bshowall.setText("SHOW ALL COOKIES");
        bshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bshowallActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRICE  RANGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR JULIAN", 0, 12))); // NOI18N

        ccrange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<", ">", "<=", ">=", "=" }));

        bselcookies.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bselcookies.setText("SELECTION");
        bselcookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselcookiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bselcookies))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ccrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(tcvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bselcookies)
                .addContainerGap())
        );

        bcclear.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bcclear.setText("CLear");
        bcclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcclearActionPerformed(evt);
            }
        });

        border.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        border.setText("ORDER");
        border.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        back.setText("BACK TO MAIN PAGE");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bshowall)
                                .addGap(42, 42, 42)
                                .addComponent(bcclear))
                            .addComponent(lcpic, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(border)
                                .addGap(102, 102, 102))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcclear)
                            .addComponent(bshowall))
                        .addGap(38, 38, 38)
                        .addComponent(lcpic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(border)
                        .addGap(51, 51, 51)
                        .addComponent(back)
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bshowallActionPerformed
   bcclear.doClick();
        DefaultTableModel dm=(DefaultTableModel)tcookies.getModel();
try{
    Class.forName("java.sql.Driver");/*It loads the driver.
    The DriverManager will try to load the driver and then for any given connection 
    request, it will ask the driver in turn to try to connect to the target URL.*/
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
    //System.out.println("connected");
    Statement s1=con.createStatement();
    String sql="Select * from Cookie;";
    ResultSet r1=s1.executeQuery(sql);
    String  id=null,name=null;
    int price=0;
    while(r1.next())
    {
        id=r1.getString(1);
        name =r1.getString(2);
        price=r1.getInt(3);
        dm.addRow(new Object[]{id,name,price});
    }
}
catch(Exception ex){
    System.out.println(ex);
}

tcookies.changeSelection(0, 0, false, false);
int j=tcookies.getSelectedRow();
//System.out.print("  "+j);
String pic=(String) dm.getValueAt(j, 0);
if(pic.equals("C1"))
    lcpic.setIcon(new ImageIcon(getClass().getResource("/choco.jpg")));
        
tcookies.requestFocus();
tcookies.editCellAt(0,1);
// TODO add your handling code here:
}//GEN-LAST:event_bshowallActionPerformed

    private void bselcookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselcookiesActionPerformed
   bcclear.doClick();
   DefaultTableModel dm=(DefaultTableModel)tcookies.getModel();
   try{
     Class.forName("java.sql.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
     //System.out.println("connected");
     Statement s1=con.createStatement();
     String sym=(String)ccrange.getSelectedItem();

     int Val=Integer.parseInt(tcvalue.getText());
     String sql="Select * from Cookie where price_per_piece"+sym+Val+";";
     ResultSet r1=s1.executeQuery(sql);
     String  id=null,name=null;
     int price=0;
     while(r1.next())
     {
        id=r1.getString(1);
        name =r1.getString(2);
        price=r1.getInt(3);
        dm.addRow(new Object[]{id,name,price});
     }
   }
   catch(Exception ex)
   {
      System.out.println(ex);
   } 

tcookies.changeSelection(0, 0, false, false);
int j=tcookies.getSelectedRow();
System.out.print("  "+j);
String pic=(String) dm.getValueAt(j, 0);
if(pic.equals("C7"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/special.JPG")));
        if(pic.equals("C5"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choclatecookie.JPG")));
        if(pic.equals("C1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco.jpg")));
        if(pic.equals("C3"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/cash.JPG")));
        if(pic.equals("C4"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/almond.jpg")));
        if(pic.equals("C6"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/walnut.JPG")));
        if(pic.equals("C2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/coffee.JPG")));
        
tcookies.requestFocus();
tcookies.editCellAt(0,1);
// TODO add your handling code here:
}//GEN-LAST:event_bselcookiesActionPerformed

    private void bcclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcclearActionPerformed

 DefaultTableModel dm=(DefaultTableModel)tcookies.getModel();
 int rc=dm.getRowCount();
 for(int i=rc-1;i>=0;i--)
     dm.removeRow(i);
 lcpic.setIcon(null);


 // TODO add your handling code here:
}//GEN-LAST:event_bcclearActionPerformed

    private void borderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderActionPerformed
        DefaultTableModel dm1= (DefaultTableModel)tcookies.getModel();
        int i=tcookies.getSelectedRow();
        //System.out.print("  "+i);
        String name=(String) dm1.getValueAt(i, 1);
        Object pr=dm1.getValueAt(i,2);
        new bill(name,pr).setVisible(true);

    }//GEN-LAST:event_borderActionPerformed

    private void tcookiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcookiesMouseClicked
        DefaultTableModel dm1= (DefaultTableModel)tcookies.getModel();
        int j=tcookies.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("C7"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/special.JPG")));
        if(pic.equals("C5"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choclatecookie.JPG")));
        if(pic.equals("C1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco.jpg")));
        if(pic.equals("C3"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/cash.JPG")));
        if(pic.equals("C4"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/almond.jpg")));
        if(pic.equals("C6"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/walnut.JPG")));
        if(pic.equals("C2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/coffee.JPG")));        // TODO add your handling code here:
    }//GEN-LAST:event_tcookiesMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void tcookiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcookiesKeyReleased
        DefaultTableModel dm1= (DefaultTableModel)tcookies.getModel();
        int j=tcookies.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("C7"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/special.JPG")));
        if(pic.equals("C5"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choclatecookie.JPG")));
        if(pic.equals("C1"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/choco.jpg")));
        if(pic.equals("C3"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/cash.JPG")));
        if(pic.equals("C4"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/almond.jpg")));
        if(pic.equals("C6"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/walnut.JPG")));
        if(pic.equals("C2"))
            lcpic.setIcon(new ImageIcon(getClass().getResource("/coffee.JPG")));         // TODO add your handling code here:
    }//GEN-LAST:event_tcookiesKeyReleased

    /**
    * @param args the command line arguments
    */  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cookies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bcclear;
    private javax.swing.JButton border;
    private javax.swing.JButton bselcookies;
    private javax.swing.JButton bshowall;
    private javax.swing.JComboBox ccrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcpic;
    private javax.swing.JTable tcookies;
    private javax.swing.JTextField tcvalue;
    // End of variables declaration//GEN-END:variables

}
