import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * doughnut.java
 *
 * Created on Jan 30, 2013, 11:16:28 AM
 */

/**
 *
 * @author LAB1
 */
public class doughnut extends javax.swing.JFrame {

    /** Creates new form doughnut */
    public doughnut() {
        initComponents();
        getContentPane().setBackground(Color.decode("#fdffcc"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdoughnut = new javax.swing.JTable();
        bshowall = new javax.swing.JButton();
        cle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        drange = new javax.swing.JComboBox();
        dvalue = new javax.swing.JTextField();
        bseldoughnut = new javax.swing.JButton();
        border = new javax.swing.JButton();
        dlab = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOUGHNUTS !!");

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOUGHNUTS MENU !!");

        tdoughnut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "Flavours", "Price_per_piece"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tdoughnut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdoughnutMouseClicked(evt);
            }
        });
        tdoughnut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tdoughnutKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tdoughnut);

        bshowall.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bshowall.setText("Show All Tables");
        bshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bshowallActionPerformed(evt);
            }
        });

        cle.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        cle.setText("Clear");
        cle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Range"));

        drange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<", ">", "<=", ">=", "=" }));

        bseldoughnut.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        bseldoughnut.setText("SELECTION");
        bseldoughnut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseldoughnutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bseldoughnut))
                    .addComponent(dvalue, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bseldoughnut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        border.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        border.setText("ORDER");
        border.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        back.setText("BACK TO MAIN PAGE");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dlab, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bshowall)
                        .addGap(48, 48, 48)
                        .addComponent(cle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(border)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bshowall)
                            .addComponent(cle))
                        .addGap(27, 27, 27)
                        .addComponent(dlab, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(border)
                        .addGap(48, 48, 48)
                        .addComponent(back)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bshowallActionPerformed
cle.doClick();
        DefaultTableModel dm=(DefaultTableModel)tdoughnut.getModel();
try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
    //System.out.println("connected");
    Statement s1=con.createStatement();
    String sql="Select * from doughnut;";
    ResultSet r1=s1.executeQuery(sql);
    String  id=null,name=null;
    int price=0;
    while(r1.next())
    {
        id=r1.getString(1);
        name =r1.getString(2);
        price=r1.getInt(3);
        dm.addRow(new Object[]{id,name,price});
    }
}
catch(Exception ex){
    System.out.println(ex);
}      
        tdoughnut.changeSelection(0, 0, false, false);
        int j=tdoughnut.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm.getValueAt(j, 0);
        if(pic.equals("D1"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/Chocolate_Doughnut.jpeg")));
        
        tdoughnut.requestFocus();
        tdoughnut.editCellAt(0,1);
// TODO add your handling code here:
}//GEN-LAST:event_bshowallActionPerformed

    private void cleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleActionPerformed
 DefaultTableModel dm=(DefaultTableModel)tdoughnut.getModel();
 int rc=dm.getRowCount();
 for(int i=rc-1;i>=0;i--)
     dm.removeRow(i); 
 dlab.setIcon(null); 
// TODO add your handling code here:
    }//GEN-LAST:event_cleActionPerformed

    private void bseldoughnutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseldoughnutActionPerformed
cle .doClick();
DefaultTableModel dm=(DefaultTableModel)tdoughnut.getModel();
try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
    //System.out.println("connected");
    Statement s1=con.createStatement();
    String sym=(String)drange.getSelectedItem();

    int Val=Integer.parseInt(dvalue.getText());
    String sql="Select * from doughnut where price_per_piece"+sym+Val+";";
    ResultSet r1=s1.executeQuery(sql);
    String  id=null,name=null;
    int price=0;
    while(r1.next())
    {
        id=r1.getString(1);
        name =r1.getString(2);
        price=r1.getInt(3);
        dm.addRow(new Object[]{id,name,price});
    }


}
catch(Exception ex)
{
    System.out.println(ex);
}     

        tdoughnut.changeSelection(0, 0, false, false);
        int j=tdoughnut.getSelectedRow();
       // System.out.print("  "+j);
        String pic=(String) dm.getValueAt(j, 0);
        if(pic.equals("D1"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/Chocolate_Doughnut.jpeg")));
        if(pic.equals("D2"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/walnut doughnut.jpg")));
        if(pic.equals("D3"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/orange_doughnut.jpg")));
        if(pic.equals("D4"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/gems_doughnut.jpg")));
        if(pic.equals("D5"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/strwaberry_doughnut.jpg")));
        if(pic.equals("D6"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/hot_chocolate_doughnut.jpg")));
        
        tdoughnut.requestFocus();
        tdoughnut.editCellAt(0,1);
// TODO add your handling code here:
    }//GEN-LAST:event_bseldoughnutActionPerformed

    private void borderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderActionPerformed
DefaultTableModel dm1= (DefaultTableModel)tdoughnut.getModel();
        int i=tdoughnut.getSelectedRow();
        //System.out.print("  "+i);
        String name=(String) dm1.getValueAt(i, 1);
        Object pr=dm1.getValueAt(i,2);
        new bill(name,pr).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_borderActionPerformed

    private void tdoughnutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdoughnutMouseClicked
        DefaultTableModel dm1= (DefaultTableModel)tdoughnut.getModel();
        int j=tdoughnut.getSelectedRow();
        //System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("D1"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/Chocolate_Doughnut.jpeg")));
        if(pic.equals("D2"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/walnut doughnut.jpg")));
        if(pic.equals("D3"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/orange_doughnut.jpg")));
        if(pic.equals("D4"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/gems_doughnut.jpg")));
        if(pic.equals("D5"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/strwaberry_doughnut.jpg")));
        if(pic.equals("D6"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/hot_chocolate_doughnut.jpg")));
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_tdoughnutMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void tdoughnutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdoughnutKeyReleased
        DefaultTableModel dm1= (DefaultTableModel)tdoughnut.getModel();
        int j=tdoughnut.getSelectedRow();
       // System.out.print("  "+j);
        String pic=(String) dm1.getValueAt(j, 0);
        if(pic.equals("D1"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/Chocolate_Doughnut.jpeg")));
        if(pic.equals("D2"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/walnut doughnut.jpg")));
        if(pic.equals("D3"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/orange_doughnut.jpg")));
        if(pic.equals("D4"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/gems_doughnut.jpg")));
        if(pic.equals("D5"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/strwaberry_doughnut.jpg")));
        if(pic.equals("D6"))
            dlab.setIcon(new ImageIcon(getClass().getResource("/hot_chocolate_doughnut.jpg")));        // TODO add your handling code here:
    }//GEN-LAST:event_tdoughnutKeyReleased
  
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doughnut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton border;
    private javax.swing.JButton bseldoughnut;
    private javax.swing.JButton bshowall;
    private javax.swing.JButton cle;
    private javax.swing.JLabel dlab;
    private javax.swing.JComboBox drange;
    private javax.swing.JTextField dvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdoughnut;
    // End of variables declaration//GEN-END:variables

}
