
import java.awt.event.*;
import javax.swing.Timer;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Oct 30, 2012, 9:15:37 AM
 */

/**
 *
 * @author optional
 */
public class NewJFrame extends javax.swing.JFrame {
    int p=1;
    Timer t1=new Timer(1000,new ActionListener(){
    public void actionPerformed(ActionEvent e)
    {
        switch(p)
        {
            case 1:jLabel2.setIcon(new ImageIcon(getClass().getResource("/20090305_JacksBakery02.jpg")));break;
            case 2:jLabel2.setIcon(new ImageIcon(getClass().getResource("/tumblr_lg01ddS4j51qbmwxno1_500.jpg")));break;
            case 3:jLabel2.setIcon(new ImageIcon(getClass().getResource("/cupcake-com-cookies_large.jpg")));break;
            case 4:jLabel2.setIcon(new ImageIcon(getClass().getResource("/PastriesAndCakesSquareWindow.jpg")));break;
            case 5:jLabel2.setIcon(new ImageIcon(getClass().getResource("/doughnuts227105929_std.jpg")));break;
            case 6:jLabel2.setIcon(new ImageIcon(getClass().getResource("/dumaguete_cakes_pastries4.jpg")));break;
                
        }
     if(p==6)
     { p=1;
     }
        
     else
        p++;
    }
});

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        bill = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutUs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        HomeMenu = new javax.swing.JMenu();
        OrderTable = new javax.swing.JMenuItem();
        OrderMenu = new javax.swing.JMenu();
        cookiesMenuItem = new javax.swing.JMenuItem();
        doughnutsMenuItem = new javax.swing.JMenuItem();
        cupcakesMenuItem = new javax.swing.JMenuItem();
        cakesMenuItem = new javax.swing.JMenuItem();
        pastriesMenuItem = new javax.swing.JMenuItem();
        ContactMenu = new javax.swing.JMenu();

        jDialog1.setTitle("BILL !!");
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 1300, 600));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton3.setText("order table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNAME", "CNO", "DDELIVERY", "DTIME", "INAME", "PRICE", "QUANTITY", "MESSAGE_ON_CAKE", "TAMOUNT"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel3.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel3.setText("                   Owner's  Window");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("LOGIN"));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setText("Login  Password");

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton1.setText("click me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BAKERY BITS !!");
        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(102, 51, 0));
        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BAKERY BITS !!");
        jLabel1.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dumaguete_cakes_pastries4.jpg"))); // NOI18N

        aboutUs.setFont(new java.awt.Font("Broadway", 1, 14)); // NOI18N
        aboutUs.setText("ABOUT US ");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        jButton2.setText("CLEAR YOUR PREVIOUS BILL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 102, 0));

        HomeMenu.setText("HOME");
        HomeMenu.setToolTipText("your bill");
        HomeMenu.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N

        OrderTable.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        OrderTable.setText("Order Table");
        OrderTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderTableActionPerformed(evt);
            }
        });
        HomeMenu.add(OrderTable);

        jMenuBar1.add(HomeMenu);

        OrderMenu.setText("ORDER");
        OrderMenu.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        OrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMenuActionPerformed(evt);
            }
        });

        cookiesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        cookiesMenuItem.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        cookiesMenuItem.setText("Cookies");
        cookiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookiesMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(cookiesMenuItem);

        doughnutsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        doughnutsMenuItem.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        doughnutsMenuItem.setText("Doughnuts");
        doughnutsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doughnutsMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(doughnutsMenuItem);

        cupcakesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        cupcakesMenuItem.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        cupcakesMenuItem.setText("Cupcakes");
        cupcakesMenuItem.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                cupcakesMenuItemMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        cupcakesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupcakesMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(cupcakesMenuItem);

        cakesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        cakesMenuItem.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        cakesMenuItem.setText("Cakes ");
        cakesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakesMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(cakesMenuItem);

        pastriesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        pastriesMenuItem.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        pastriesMenuItem.setText("Pastries");
        pastriesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastriesMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(pastriesMenuItem);

        jMenuBar1.add(OrderMenu);

        ContactMenu.setText("CONTACT");
        ContactMenu.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        ContactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ContactMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
new about().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
t1.start();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void OrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMenuActionPerformed
//new order().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_OrderMenuActionPerformed

    private void cookiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookiesMenuItemActionPerformed
new cookies().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_cookiesMenuItemActionPerformed

    private void ContactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMenuMouseClicked
new contact().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ContactMenuMouseClicked

    private void cupcakesMenuItemMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_cupcakesMenuItemMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupcakesMenuItemMenuKeyPressed

    private void cupcakesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupcakesMenuItemActionPerformed
new cupcake().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cupcakesMenuItemActionPerformed

    private void OrderTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderTableActionPerformed
jDialog1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_OrderTableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String psw=new String (jPasswordField1.getPassword());
if(psw.equals("cupncake"))
{
jButton3.setEnabled(true);
jTable5.setEnabled(true);
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
       jButton3.setEnabled(false);
       jTable5.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jDialog1WindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel dm=(DefaultTableModel)jTable5.getModel();
  int rc=dm.getRowCount();
  for(int i=rc-1;i>=0;i--)
      dm.removeRow(i);
  try{
    Class.forName("java.sql.Driver"); /*It loads the driver.
    The DriverManager will try to load the driver and then for any given connection 
    request, it will ask the driver in turn to try to connect to the target URL.*/
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
    //System.out.println("connected");
    Statement s1=con.createStatement();
    Statement s2=con.createStatement();
    String sql="Select * from bill;";
    String sql2="Select sum(AMOUNT) from bill;";
    ResultSet r1=s1.executeQuery(sql);
    //The object of ResultSet maintains a cursor pointing to a row of a table. 
    //Initially, cursor points to before the first row.
    ResultSet r2=s2.executeQuery(sql2);
    String  cname=null,cno=null,ddel=null,dtime=null,iname=null,msg=null;

    int price=0,qnt=0,amnt=0, tamnt = 0;
    while(r1.next())
    {
        cname=r1.getString(1);
        cno =r1.getString(2);
        ddel =r1.getString(3);
        dtime=r1.getString(4);
        iname=r1.getString(5);
        msg=r1.getString(8);
        price=r1.getInt(6);
        qnt=r1.getInt(7);
        amnt=r1.getInt(9);
        dm.addRow(new Object[]{cname,cno,ddel,dtime,iname,price,qnt,msg,amnt});
    }
    while(r2.next()){
        tamnt = r2.getInt(1);
        bill.setText("YOUR TOTAL BILL AMOUNT IS RS. " + tamnt + ".");
    }
}
catch(Exception ex)
{
    System.out.println(ex);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void doughnutsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doughnutsMenuItemActionPerformed
new doughnut().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_doughnutsMenuItemActionPerformed

    private void cakesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakesMenuItemActionPerformed
 new cake().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_cakesMenuItemActionPerformed

    private void pastriesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastriesMenuItemActionPerformed
  new Pastry().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_pastriesMenuItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.Driver");       
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3305/project","root","tiger");
            System.out.println("connected");
            Statement s1=con.createStatement();
            String sql="delete from bill;";
            int r1=s1.executeUpdate(sql);  
    } catch (Exception ex) {
            ex.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ContactMenu;
    private javax.swing.JMenu HomeMenu;
    private javax.swing.JMenu OrderMenu;
    private javax.swing.JMenuItem OrderTable;
    private javax.swing.JButton aboutUs;
    private javax.swing.JLabel bill;
    private javax.swing.JMenuItem cakesMenuItem;
    private javax.swing.JMenuItem cookiesMenuItem;
    private javax.swing.JMenuItem cupcakesMenuItem;
    private javax.swing.JMenuItem doughnutsMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JMenuItem pastriesMenuItem;
    // End of variables declaration//GEN-END:variables

}
